config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/search', to: 'searches#search'
  get 'home/about' => 'homes#about'
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :index, :edit, :update, :create] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = @book.book_comments.build(book_comment_params)
    @comment.user_id = current_user.id
    @comment.save
  end

  def destroy
    @comment = BookComment.find(params[:id])
    @comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment, :book_id, :user_id)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_count.html.erb
コメント件数：<%= book.count %>

app/views/book_comments/_index.html.erb
<table>
  <% book.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to user_path(book_comment.user.id) do %>
          <%= attachment_image_tag book_comment.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td>
        <%= book_comment.comment %>
      </td>
      <td class="align-self-center">
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: "btn btn-sm btn-danger", method: :delete, remote: true %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/book_comments/create.js.erb
$("#comments_area").html("<%= j(render 'book_comments/index', { book: @comment.book.book_comments }) %>")
$("#counts_area").html("<%= j(render 'book_comments/count', { book: @comment.book.book_comments }) %>")
(".input-mysize").val('')

app/views/book_comments/destroy.js.erb
$('#comments_area').html("<%= j(render "book_comments/index", { book: @comment.book.book_comments }) %>")