config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/search', to: 'searches#search'
  get 'home/about' => 'homes#about'
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :index, :edit, :update, :create] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments,dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title,presence: { message: 'error' }

  validates :body,presence: { message: 'error' }
  validates :body,length: { maximum: 200 }


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_books,only: [:edit]

  def correct_books
        @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end



  def create
    @book = Book.new(book_params)
    # Bookモデルに新しいやつを入れる
    @book.user_id = current_user.id
   if @book.save
     flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
      # 元々Bookモデルにはidが複数あり、@book.idで最新のものを持ってくる
      # パスにparamsは入れられない。
   else
     @user = current_user
     @books = Book.page(params[:page]).reverse_order
      render :index
   end
  end

  def index
    @book = Book.new

    @user = current_user
    @books = Book.page(params[:page]).reverse_order
  end

  def show
    @book_new = Book.new
    @book_comment = BookComment.new
    @book = Book.find(params[:id])
    @user = current_user
    @comments = @book.book_comments.order(created_at: :desc)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path

    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %>件のerrorが発生しました
  <% book.errors.full_messages.each do |message| %>
    <%= message %>
    <p>can't be blank</p>
  <% end %>
<% end %>

<% if usermy.errors.any? %>
  <%= usermy.errors.count %>件のerrorが発生しました
  <% usermy.errors.full_messages.each do |message| %>
    <%= message %>
    <p>can't be blank</p>
  <% end %>
<% end %>

<div>
  <div class="w-50 mx-auto">
    <% if user_signed_in? %>
      <%= form_tag(search_path, method: :get) do %>
        <%= text_field_tag 'content' %>
        <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "books" }) %>
        <%= select_tag 'method', options_for_select({ "完全一致" => "perfect_match", "部分一致" => "partial_match", "前方一致" => "forward_match", "後方一致" => "backward_match" }) %>
        <%= submit_tag '検索' %>
      <% end %>
    <% end %>
  </div>

  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag usermy, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= usermy.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= usermy.introduction %></th>
            </tr>
            <tr>
              <th><p class="text-small"><%= link_to usermy.followings.count, followings_user_path(usermy) %> フォロー</p></th>
            </tr>
            <tr>
              <th><p class="text-small"><%= link_to usermy.followers.count, followers_user_path(usermy) %> フォロワー</p></th>
            </tr>
            <tr>
              <th>
                <% if usermy != current_user %>
                  <% if usermy.is_followed_by?(current_user) %>
                    <%=link_to user_relationships_path(usermy), method: :delete do %>
                      <button type="button" class="btn btn btn-danger">フォロー解除</button>
                    <% end %>
                  <% else %>
                    <%=link_to user_relationships_path(usermy), method: :post do %>
                      <button type="button" class="btn btn btn-primary">フォロー</button>
                    <% end %>
                  <% end %>
                <% end %>
              </th>
            </tr>
          </tbody>
        </table>

          <% if usermy.id == current_user.id %>
            <%= link_to edit_user_path(usermy) do %>
            <div class="row">
            <p class="btn btn-outline-secondary btn-block fas fa-user-cog"></p>
            </div>
            <% end %>
          <% end %>

        <h2 class="mt-3">New book</h2>
          <%= form_with model: book, url:'/books', local:true do |f| %>
            <p>title</p>
            <%= f.text_field :title %>
            <p>Opinion</p>
            <%= f.text_area :body %>
            <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
          <% end %>
      </div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model:@book, local:true do |f| %>
      <div>
        <label for="inputTitle">Title</label>
        <p><%= f.text_field :title, autofocus: true, id:"inputTitle" %></p>
      </div>
      <div>
        <label for="inputBody">Opinion</label>
        <p><%= f.text_area :body, autofocus: true, id:"inputBody" %></p>
      </div>
      <div class="mb-3">
         <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
      <% end %>
      </div>
      <div>
      <%= link_to "Show", book_path %> | <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'books/list',usermy: @user, book: @book %>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <% @books.each do |book| %>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
                <% end %>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td id="favorite_buttons_<%= book.id %>">
                <%= render 'favorites/favorite', book: book %>
              </td>
              <td>
                <p>コメント件数：<%= book.book_comments.count %></p>
              </td>
            </tr>
          </tbody>
        </table>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= paginate @books %>

app/views/books/show.html.erb
<div>
  <div class="w-50 mx-auto">
    <% if user_signed_in? %>
      <%= form_tag(search_path, method: :get) do %>
        <%= text_field_tag 'content' %>
        <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "books" }) %>
        <%= select_tag 'method', options_for_select({ "完全一致" => "perfect_match", "部分一致" => "partial_match", "前方一致" => "forward_match", "後方一致" => "backward_match" }) %>
        <%= submit_tag '検索' %>
      <% end %>
    <% end %>
  </div>

  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <h2>User info</h2>
        <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @book.user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @book.user.introduction %></th>
            </tr>
          </tbody>
        </table>

        <%= link_to edit_user_path(@book.user) do %>
        <div class="row">
        <p class="btn btn-outline-secondary btn-block fas fa-user-cog"></p>
        </div>
        <% end %>

        <h2 class="mt-3">New book</h2>
          <%= form_with model: @book_new, local:true do |f| %>
            <p>title</p>
            <%= f.text_field :title %>
            <p>Opinion</p>
            <%= f.text_area :body %>
            <input type="submit" names="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
          <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user.id) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></br>
                <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
                <% end %>
              </td>
              <td><%= @book.body %></td>
              <td>
                <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>
                <% end %>
              </td>
              <td>
                <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book), class: "btn btn-sm btn-danger", data: {confirm: "本当に消しますか？"}, method: :delete %>
                <% end %>
              </td>
              <td id="favorite_buttons_<%= @book.id %>">
                <%= render 'favorites/favorite', book: @book %>
              </td>
              <td id="counts_area">
                <%= render partial: 'book_comments/count', locals: { book: @comments } %>
              </td>
            </tr>
          </tbody>
        </table>

        <div class="d-flex" id="comments_area">
           <%= render partial: 'book_comments/index', locals: { book: @comments } %>
        </div>
        <div>
          <%#= render partial: 'book_comments/commentnew', locals: { book_comment: @book_comment, book: @book } %>
          <%= form_with(model:[@book, @book_comment], url: book_book_comments_path(@book) ) do |f| %>
            <%= f.text_area :comment, class: "input-mysize"  %>
            <p><%= f.submit "送信" %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>