config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/search', to: 'searches#search'
  get 'home/about' => 'homes#about'
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :index, :edit, :update, :create] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments,dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title,presence: { message: 'error' }

  validates :body,presence: { message: 'error' }
  validates :body,length: { maximum: 200 }


end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
  

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_many :favorites, dependent: :destroy

  has_many :book_comments, dependent: :destroy

  # フォローする側から中間テーブルへのアソシエーション
  has_many :relationships, foreign_key: :following_id
  # フォローする側からフォローされたユーザを取得する
  has_many :followings, through: :relationships, source: :follower

  # フォローされる側から中間テーブルへのアソシエーション
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  # フォローされる側からフォローしているユーザを取得する
  has_many :followers, through: :reverse_of_relationships, source: :following

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

  attachment :profile_image

  validates :name,presence: { message: 'error' }
  validates :name, uniqueness: { case_sensitive: false }
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
       flash[:notice] = "Signed in successfully."
       user_path(resource)
  end

  def after_inactive_sign_up_path_for(resource)
       flash[:notice] = "Welcome! You have signed up successfully."
       user_path(resource)
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_books,only: [:edit]

  def correct_books
        @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end



  def create
    @book = Book.new(book_params)
    # Bookモデルに新しいやつを入れる
    @book.user_id = current_user.id
   if @book.save
     flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
      # 元々Bookモデルにはidが複数あり、@book.idで最新のものを持ってくる
      # パスにparamsは入れられない。
   else
     @user = current_user
     @books = Book.page(params[:page]).reverse_order
      render :index
   end
  end

  def index
    @book = Book.new

    @user = current_user
    @books = Book.page(params[:page]).reverse_order
  end

  def show
    @book_new = Book.new
    @book_comment = BookComment.new
    @book = Book.find(params[:id])
    @user = current_user
    @comments = @book.book_comments.order(created_at: :desc)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path

    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.build(book_id: params[:book_id])
    favorite.save

  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
    favorite.destroy

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    # viewのform_tagにて
    # 選択したmodelの値を@modelに代入。
    @model = params["model"]
    # 選択した検索方法の値を@methodに代入。
    @method = params["method"]
    # 検索ワードを@contentに代入。
    @content = params["content"]
    # @model, @content, @methodを代入した、
    # search_forを@recordsに代入。
    @records = search_for(@model, @content, @method)
  end

  private

  def search_for(model, content, method)
    # 選択したモデルがuserだったら
    if model == 'user'
      if method == "forward_match"
        User.where("name LIKE?","%#{content}")
      elsif method == "backward_match"
        User.where("name LIKE?","#{content}%")
      elsif method == "perfect_match"
        User.where(name: "#{content}")
      elsif method == "partial_match"
        User.where("name LIKE?","%#{content}%")
      end
    # 選択したモデルがbookだったら
    elsif model == 'books'
      if method == "forward_match"
        Book.where("title LIKE?","%#{content}")
      elsif method == "backward_match"
          Book.where("title LIKE?","#{content}%")
      elsif method == "perfect_match"
          Book.where(title: "#{content}")
      elsif method == "partial_match"
          Book.where("title LIKE?","%#{content}%")
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_users,only: [:edit]

  def correct_users
        @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = User.find(params[:id])
    @booksall = Book.all
    @books = @booksall.page(params[:page]).reverse_order
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @users = User.all
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(current_user.id)

    else
      render :index
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @book = Book.new
    @usermy = current_user
    @users = User.page(params[:page]).reverse_order
    @users_follow = User.where.not(id: current_user.id)

  end

  def followings
    @user = current_user
    @book = Book.new
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    @user = current_user
    @book = Book.new
    user = User.find(params[:id])
    @users = user.followers
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user.id)

    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-16px py-8px">
        <div class="container">
          <a class="navbar-brand text-white py-5px" href="/">Bookers</a>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
              <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-white' do %>
              <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-white' do %>
              <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
              <i class="fas fa-sign-out-alt"></i> logout
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-white' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
            </li>
            <li class="nav-item">
              <%= link_to home_about_path, class: 'nav-link text-white' do %>
              <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
              <i class="fas fa-user-plus"></i> sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
              <i class="fas fa-sign-in-alt"></i> login
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
    <%= flash[:notice] %>
    <%= yield %>
    </main>

    <footer class="text-black">
      <div class="container mt-5">
        <div class="row">
          <div class="col d-flex justify-content-center">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>